#!/bin/bash
echo "enter filename"
read filename
num=1
while read line
do
        count=`echo $line | wc -w`
        echo "the number of words in line $num is $count"
        num=`expr $num + 1`
done < $filename
